# Generated by Django 5.0 on 2023-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('fr', 'free'), ('bc', 'basic'), ('pr', 'pro'), ('pm', 'premium')], default='fr', max_length=20, verbose_name='Post tag'),
        ),
    ]
